# Game
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 400
FPS = 60
FLOOR = 370
VOLUME = 0.5
BACKGROUND_X = 3
GAME_NAME_Y = 50
START_MSG_Y = 360
BACKGROUND_PATH = 'graphics/background.png'
MUSIC_AUDIO_PATH = 'audio/music.wav'
JUMP_AUDIO_PATH = 'audio/jump.wav'

# Player
PLAYER_X = 80
PLAYER_RUN_INCREMENTS = 0.15
PLAYER_JUMP_INCREMENTS = 0.25
GRAVITY = -20

# Obstacle
HIGH_OBSTACLE_OFFSET = 100
MID_OBSTACLE_OFFSET = 20
OBSTACLE_INCREMENTS = 0.1
OBSTACLE_X = [900, 1100]
OBSTACLE_Y_INCREMENTS = 6
OBSTACLE_TIMER_INTERVAL = 1700

# Score
CURRENT_SCORE_X = 400
CURRENT_SCORE_Y = 30
FINAL_SCORE_Y = 320
SCORE_COLOR = 'white'

# Pause
PAUSED_Y = 180
ESCAPED_Y = 220
PAUSED_COLOR = 'grey'
ESCAPE_COLOR = 'grey'

# Idle
IDLE_INCREMENTS = 0.2
IDLE_NO_SCORE_Y = 310
IDLE_SCORE_Y = 290
GAME_NAME_COLOR = 'pink'
GAME_SUB_TEXT = "by Amelia Li"

# Font
FONT_PATH = 'font/04b_30.ttf'
GAME_FONT_BIG_SIZE = 50
GAME_FONT_REG_SIZE = 30
GAME_FONT_SM_SIZE = 25
GAME_FONT_X_SM_SIZE = 20

# Sprites
Y_POSITIONS_RUN = [0, 25, 67, 94, 120, 145, 187, 214]
Y_POSITIONS_JUMP = [-3, 23, 50, 77, 121, 161, 204, 245, 270, 295, 321, 347]
Y_POSITIONS_IDLE = [0, 26, 52, 78, 104, 130]
MOUSE_POSITIONS = [0, 16, 32, 48]
RUN_SPRITESHEET_PATH = 'graphics/player/run_spritesheet.png'
JUMP_SPRITESHEET_PATH = 'graphics/player/jump_spritesheet.png'
IDLE_SPRITESHEET_PATH = 'graphics/player/idle_spritesheet.png'
MOUSE_SPRITESHEET_PATH = 'graphics/mouse/spritesheet.png'

COLORKEY = (0, 0, 0)

RUN_WIDTH = 13
RUN_HEIGHT = 16
RUN_START_X = 2
RUN_SCALE = 6

JUMP_WIDTH = 12
JUMP_HEIGHT = 19
JUMP_START_X = 2
JUMP_SCALE = 6

IDLE_WIDTH = 13
IDLE_HEIGHT = 16
IDLE_START_X = 1
IDLE_SCALE = 11

MOUSE_WIDTH = 16
MOUSE_HEIGHT = 16
MOUSE_START_X = 32
MOUSE_SCALE = 4

RUN_SPRITESHEET_ARGS = [(RUN_WIDTH, RUN_HEIGHT, RUN_START_X, y, RUN_SCALE, COLORKEY) for y in Y_POSITIONS_RUN]
JUMP_SPRITESHEET_ARGS = [(JUMP_WIDTH, JUMP_HEIGHT, JUMP_START_X, y, JUMP_SCALE, COLORKEY) for y in Y_POSITIONS_JUMP]
IDLE_SPRITESHEET_ARGS = [(IDLE_WIDTH, IDLE_HEIGHT, IDLE_START_X, y, IDLE_SCALE, COLORKEY) for y in Y_POSITIONS_IDLE]
MOUSE_SPRITESHEET_ARGS = [(MOUSE_WIDTH, MOUSE_HEIGHT, MOUSE_START_X, y, MOUSE_SCALE, COLORKEY) for y in MOUSE_POSITIONS]